const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const html = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8');
const css = fs.readFileSync(path.join(__dirname, '..', 'styles.css'), 'utf8');
const js = fs.readFileSync(path.join(__dirname, '..', 'app.js'), 'utf8');
const pkg = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'package.json'), 'utf8'));

assert.match(html, /<div class="action-group adds">[\s\S]*id="add-red"[\s\S]*id="add-blue"[\s\S]*id="add-shuttle"[\s\S]*<\/div>/);
assert.equal(pkg.version, '1.0.1');
assert.match(html, /og:url" content="https:\/\/badmintonmind\.netlify\.app\//);
assert.match(html, /og:image" content="https:\/\/badmintonmind\.netlify\.app\/assets\/yonex\.jpeg"/);
assert.doesNotMatch(html, /badminton-tactic-board-neo111282\.netlify\.app/);
assert.match(html, /<div class="action-group ops">[\s\S]*id="undo"[\s\S]*id="delete"[\s\S]*id="clear"[\s\S]*id="save"[\s\S]*<\/div>/);
assert.match(html, /<div class="action-group share">[\s\S]*id="github-repo"[\s\S]*id="contact-author"[\s\S]*id="contact-card"[\s\S]*id="github-card"[\s\S]*<\/div>/);
assert.match(html, /<span class="contact-card-value"[^>]*role="button"[^>]*>xiaonaneo1990<\/span>/);
assert.match(css, /\.toolbar\s*\{[^}]*justify-content:\s*space-between;/is);
assert.match(css, /\.toolbar\s*\{[^}]*padding:\s*14px 0;/is);
assert.match(css, /@media \(max-width: 560px\)[\s\S]*\.toolbar\s*\{[^}]*display:\s*grid;[^}]*grid-template-rows:\s*repeat\(4, max-content\);[^}]*align-content:\s*space-between;[^}]*padding:\s*8px 0;/is);
assert.match(css, /\.board\s*\{[^}]*border:\s*0;[^}]*background:\s*transparent;[^}]*box-shadow:\s*none;/is);
assert.match(css, /@media \(min-width: 561px\)[\s\S]*\.board\s*\{[^}]*justify-content:\s*flex-start;[^}]*padding-right:\s*0;[^}]*padding-left:\s*0;/is);
assert.match(css, /@media \(min-width: 561px\)[\s\S]*\.board > svg\s*\{[^}]*width:\s*auto;[^}]*height:\s*100%;[^}]*margin:\s*0 auto 0 0;/is);
assert.match(css, /@media \(min-width: 561px\)[\s\S]*\.app\s*\{[^}]*grid-template-columns:\s*76px min\(520px, 49dvh\);[^}]*justify-content:\s*center;[^}]*gap:\s*8px;/is);
assert.match(css, /\.sidebar\s*\{[^}]*padding:\s*0 8px;[^}]*border:\s*0;[^}]*background:\s*transparent;/is);
assert.match(css, /@media \(max-width: 560px\)[\s\S]*\.sidebar\s*\{[^}]*padding:\s*0 5px;/is);
assert.match(css, /@media \(max-width: 560px\)[\s\S]*button\s*\{[^}]*width:\s*38px;[^}]*height:\s*38px;[^}]*min-height:\s*38px;/is);
assert.match(css, /@media \(hover: none\)[\s\S]*\.action-group:not\(\.share\) button:hover\s*\{[^}]*background:\s*transparent;/is);
assert.match(css, /@media \(hover: none\)[\s\S]*\.toolbar button, \.toolbar button:hover, \.toolbar button:active\s*\{[^}]*background:\s*transparent;[^}]*box-shadow:\s*none;/is);
assert.match(css, /@media \(hover: none\)[\s\S]*contact-trigger\.is-clicked:hover[\s\S]*color:\s*var\(--brand\);/is);
assert.match(css, /\.actions\s*\{[^}]*display:\s*contents;/is);
assert.match(css, /\.seg,\s*\.action-group,\s*\.board\s*\{[^}]*border:/is);
assert.match(css, /\.action-group:not\(\.share\) button\s*\{[^}]*background:\s*transparent;/is);
assert.match(css, /\.action-group\.share button\.primary\s*\{[^}]*background:\s*transparent;[^}]*color:\s*var\(--green\);/is);
assert.match(css, /\.action-group\.ops button\.share-button\s*\{[^}]*color:\s*var\(--text\);/is);
assert.match(css, /button:hover,\s*button\.primary:hover[^}]*border-color:\s*transparent;/is);
assert.match(css, /\.action-group:not\(\.share\) button:hover\s*\{[^}]*border-color:\s*transparent;/is);
assert.match(css, /\.seg-item:hover input:checked \+ \.control-icon\s*\{[^}]*border-color:\s*transparent;/is);
assert.match(css, /\.seg-item:hover \.control-icon, \.toolbar button:hover[\s\S]*color:\s*var\(--text\);[^}]*background:\s*transparent;/is);
assert.match(css, /button\.is-clicked \.icon\s*\{[^}]*color:\s*var\(--brand\);[^}]*filter:\s*none;/is);
assert.match(css, /\.seg-item input:checked \+ \.control-icon\s*\{[^}]*border-color:\s*transparent;/is);
assert.match(css, /\.action-group\.ops button#delete\[aria-pressed="true"\]\s*\{[^}]*border-color:\s*transparent;/is);
assert.match(css, /button:hover\s*\{[^}]*box-shadow:\s*none;/is);
assert.match(css, /button\.primary\s*\{[^}]*box-shadow:\s*none;/is);
assert.match(css, /\.contact-card\s*\{[^}]*position:\s*absolute;[^}]*z-index:\s*50;/is);
assert.match(css, /\.contact-card\s*\{[^}]*width:\s*max-content;[^}]*max-width:\s*min\(250px,\s*calc\(100vw - 24px\)\);/is);
assert.match(css, /\.contact-card\[hidden\]\s*\{[^}]*display:\s*none;/is);
assert.match(css, /@media \(max-width: 560px\)[\s\S]*#github-repo::after,[\s\S]*#contact-author::after \{\s*display:\s*none;/is);
assert.match(css, /\[data-tooltip\]:focus::after,\s*\[data-tooltip\]:focus-visible::after[\s\S]*opacity:\s*1;/is);
assert.doesNotMatch(js, /mobileTooltipControls|mobile-tooltip-visible/);
assert.doesNotMatch(html, /reward-author|reward-card|reward-qr|打赏作者/);
assert.doesNotMatch(css, /reward-trigger|reward-card/);
assert.doesNotMatch(js, /rewardButton|rewardCard/);
assert.match(js, /navigator\.clipboard\.writeText\(text\)/);
assert.match(js, /document\.execCommand\('copy'\)/);
assert.doesNotMatch(js, /图片已复制，打开微信粘贴给指定好友/);
assert.match(js, /if \(!isTouch \|\| !navigator\.share\) \{[\s\S]*showToast\('保存成功'\)/);
assert.match(js, /navigator\.share\(shareData\)\.then\(function \(\) \{\s*\/\/ 微信等分享目标完成后保持静默/);
assert.match(html, /href="https:\/\/github\.com\/xiaonaneo\/badminton-tactic-board"/);
assert.match(css, /\.github-card\[hidden\]\s*\{[^}]*display:\s*none;/is);
assert.match(js, /document\.addEventListener\('pointerdown',\s*closeAuthorCards,\s*true\);/);
assert.match(js, /authorCards\.some\(/);
assert.match(html, /id="clear-confirm"[^>]*hidden/);
assert.match(html, /id="clear-confirm-action"[^>]*>确认清空<\/button>/);
assert.match(html, /id="toast"[^>]*role="status"[^>]*aria-live="polite"/);
assert.match(js, /clearButton\.addEventListener\('click'/);
assert.match(js, /if \(!items\.length\) \{[\s\S]*showToast\('当前没有可清空的战术'\)/);
assert.match(js, /clearConfirmButton\.addEventListener\('click', clearItems\)/);
assert.match(js, /function markActionButton\(button\)[\s\S]*classList\.toggle\('is-clicked'/);
assert.match(js, /if \(button !== deleteButton\) setDeleteMode\(false\)/);
assert.match(js, /function resetActionButton\(button\)[\s\S]*classList\.remove\('is-clicked'/);
assert.match(js, /function flashResetActionButton\(button\)[\s\S]*setTimeout/);
assert.match(js, /undoButton\.addEventListener\('click', function \(\) \{[\s\S]*flashResetActionButton\(undoButton\)/);
assert.match(js, /flashResetActionButton\(saveButton\)/);
assert.match(js, /resetActionButton\(clearButton\)/);
assert.match(js, /function setAuthorCard\(entry, open\)[\s\S]*if \(!open\) resetActionButton\(entry\.button\)/);
assert.match(css, /button\.is-clicked \.icon\s*\{[^}]*color:\s*var\(--brand\);/is);
assert.match(js, /if \(e\.key === 'Tab' && !clearConfirmLayer\.hidden\)/);
assert.match(js, /items = \[\];\s*nextId = 1;\s*select\(null\);\s*scheduleCache\(\);/);
assert.match(js, /function markerOverlaps\(m, team\)[\s\S]*\(radius \+ otherRadius\) \/ window\.COURT\.SCALE/);
assert.match(js, /function nextMarkerPosition\(team\)[\s\S]*addMarker\(nextMarkerPosition\('red'\), 'red'\)/);
assert.match(js, /addMarker\(nextMarkerPosition\('blue'\), 'blue'\)/);
assert.match(js, /function activateMoveTool\(\)[\s\S]*value="select"[\s\S]*setTool\('select'\)/);
assert.match(js, /addMarker\(nextMarkerPosition\('red'\), 'red'\);\s*activateMoveTool\(\)/);
assert.match(js, /addMarker\(nextMarkerPosition\('blue'\), 'blue'\);\s*activateMoveTool\(\)/);
assert.match(js, /addMarker\(nextMarkerPosition\('shuttle'\), 'shuttle'\);\s*activateMoveTool\(\)/);
assert.match(js, /function markerRadius\(team\)/);
assert.match(js, /const radius = markerRadius\(team\);/);
assert.match(html, /id="delete"[^>]*aria-pressed="false"/);
assert.match(js, /if \(deleteMode\) \{/);
assert.match(js, /deleteButton\.addEventListener\('click'/);
assert.match(js, /if \(deleteMode \|\| tool !== 'text'\) return;/);
assert.match(js, /tool = 'select';\s*closeTextInput\(\);/);
assert.match(js, /document\.querySelectorAll\('input\[name="tool"\]'\)/);
assert.match(js, /radio\.checked = false/);
assert.match(html, /id="eraser-cursor"[^>]*aria-hidden="true"/);
assert.match(css, /\.board > svg\.tool-delete[^}]*cursor:\s*none\s*!important;/is);
assert.match(css, /\.eraser-cursor\.is-visible\s*\{[^}]*opacity:\s*1;/is);
assert.match(css, /\.eraser-cursor\.is-visible \.icon\s*\{[^}]*fill:\s*none;/is);
assert.match(js, /eraserCursor\.style\.left/);
assert.match(js, /function syncMobileSidebar\(\)/);
assert.match(js, /svg\.getBoundingClientRect\(\)\.height/);
assert.match(js, /sidebar\.style\.height = `\$\{Math\.ceil\(svgHeight \+ verticalPadding\)\}px`/);
assert.match(js, /sidebar\.style\.alignSelf = 'center'/);
