const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const html = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8');
const css = fs.readFileSync(path.join(__dirname, '..', 'styles.css'), 'utf8');
const js = fs.readFileSync(path.join(__dirname, '..', 'app.js'), 'utf8');

assert.match(html, /<div class="action-group adds">[\s\S]*id="add-red"[\s\S]*id="add-blue"[\s\S]*id="add-shuttle"[\s\S]*<\/div>/);
assert.match(html, /<div class="action-group ops">[\s\S]*id="undo"[\s\S]*id="delete"[\s\S]*id="clear"[\s\S]*id="save"[\s\S]*<\/div>/);
assert.match(html, /<div class="action-group share">[\s\S]*id="github-repo"[\s\S]*id="contact-author"[\s\S]*id="reward-author"[\s\S]*id="contact-card"[\s\S]*id="reward-card"[\s\S]*id="github-card"[\s\S]*<\/div>/);
assert.match(css, /\.seg,\s*\.action-group,\s*\.board\s*\{[^}]*border:/is);
assert.match(css, /\.action-group:not\(\.share\) button\s*\{[^}]*background:\s*transparent;/is);
assert.match(css, /\.action-group\.share button\.primary\s*\{[^}]*background:\s*transparent;[^}]*color:\s*var\(--green\);/is);
assert.match(css, /\.action-group\.ops button\.share-button\s*\{[^}]*color:\s*var\(--green\);/is);
assert.match(css, /button:hover,\s*button\.primary:hover[^}]*border-color:\s*transparent;/is);
assert.match(css, /\.action-group:not\(\.share\) button:hover\s*\{[^}]*border-color:\s*transparent;/is);
assert.match(css, /\.seg-item:hover input:checked \+ \.control-icon\s*\{[^}]*border-color:\s*transparent;/is);
assert.match(css, /\.seg-item input:checked \+ \.control-icon\s*\{[^}]*border-color:\s*transparent;/is);
assert.match(css, /\.action-group\.ops button#delete\[aria-pressed="true"\]\s*\{[^}]*border-color:\s*transparent;/is);
assert.match(css, /button:hover\s*\{[^}]*box-shadow:\s*none;/is);
assert.match(css, /button\.primary\s*\{[^}]*box-shadow:\s*none;/is);
assert.match(css, /\.contact-card\s*\{[^}]*position:\s*absolute;[^}]*z-index:\s*50;/is);
assert.match(css, /\.contact-card\[hidden\]\s*\{[^}]*display:\s*none;/is);
assert.match(css, /\.reward-card\[hidden\]\s*\{[^}]*display:\s*none;/is);
assert.match(html, /<img src="assets\/reward-qr\.jpg" alt="作者收款二维码"\s*\/>/);
assert.match(html, /href="https:\/\/github\.com\/xiaonaneo\/badminton-tactic-board"/);
assert.match(css, /\.github-card\[hidden\]\s*\{[^}]*display:\s*none;/is);
assert.match(js, /document\.addEventListener\('pointerdown',\s*closeAuthorCards,\s*true\);/);
assert.match(js, /authorCards\.some\(/);
assert.match(js, /window\.confirm\('确定清空当前战术吗？此操作不可撤回。'\)/);
assert.match(html, /id="delete"[^>]*aria-pressed="false"/);
assert.match(js, /if \(deleteMode\) \{/);
assert.match(js, /deleteButton\.addEventListener\('click'/);
assert.match(js, /document\.querySelectorAll\('input\[name="tool"\]'\)/);
assert.match(js, /radio\.checked = false/);
assert.match(html, /id="eraser-cursor"[^>]*aria-hidden="true"/);
assert.match(css, /\.board > svg\.tool-delete[^}]*cursor:\s*none\s*!important;/is);
assert.match(css, /\.eraser-cursor\.is-visible\s*\{[^}]*opacity:\s*1;/is);
assert.match(css, /\.eraser-cursor\.is-visible \.icon\s*\{[^}]*fill:\s*currentColor;/is);
assert.match(js, /eraserCursor\.style\.left/);
